config/routes.rb
Rails.application.routes.draw do
  # get 'doses/new'
  # get 'doses/create'
  # get 'doses/destroy'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
    # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :cocktails, only: [:index, :new, :create, :show, :destroy] do
    resources :doses, only: [:new, :create]
  end
  resources :doses, only: [:destroy]

  root to: "cocktails#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cocktail.rb
class Cocktail < ApplicationRecord
  mount_uploader :photo, PhotoUploader

  has_many :doses, dependent: :destroy
  has_many :ingredients, through: :doses
  validates :name, presence: true
  validates :name, uniqueness: true

end

app/models/dose.rb
class Dose < ApplicationRecord
  belongs_to :cocktail
  belongs_to :ingredient
  validates :description, presence: true
  validates :cocktail, uniqueness: { scope: :ingredient }
end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
  has_many :doses
  has_many :cocktails, through: :doses
  validates :name, presence: true
  validates :name, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/cocktails_controller.rb
class CocktailsController < ApplicationController
  def index
    @cocktails = Cocktail.all
  end

  def show
    @cocktail = Cocktail.find(params[:id])
  end

  def new
    @cocktail = Cocktail.new
  end

  def destroy
    @cocktail = Cocktail.find(params[:id])
    @cocktail.destroy
    redirect_to '/cocktails'
  end

  def create
    @cocktail = Cocktail.new(cocktail_params)
    if @cocktail.save
      redirect_to cocktail_path(@cocktail)
    else
      render :new
    end
  end

  def cocktail_params
    params.require(:cocktail).permit(:name, :photo)
  end
end

app/controllers/doses_controller.rb
class DosesController < ApplicationController
  def new
    @cocktail = Cocktail.find(params[:cocktail_id])
    @dose = Dose.new
  end

  def create
    @cocktail = Cocktail.find(params[:cocktail_id])
    @dose = Dose.new(dose_strong_params)
    @dose.cocktail = @cocktail
      if @dose.save
        redirect_to cocktail_path(@cocktail)
      else
        render :new
      end
  end

  def destroy
    @dose = Dose.find(params[:id])
    @dose.destroy
    redirect_to cocktail_path(@dose.cocktail_id)
  end

  private

  def dose_strong_params
    params.require(:dose).permit(:description, :ingredient_id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cocktails_helper.rb
module CocktailsHelper
end

app/helpers/doses_helper.rb
module DosesHelper
end

app/views/cocktails/index.html.erb
<div class="banner">
  <div class="container">
    <h1><strong>Kaveh's Cocktails!</strong></h1>
  </div>
  <div class="container">
  </div>

<div class="container">
  <div class="row">
    <% @cocktails.each do |c| %>
    <div class="col d-flex align-items-stretch">
        <div class="card mt-3 align-items-center" style="width: 15rem">

        <%= cl_image_tag c.photo %>
          <div class="card-body">
            <h5 class="card-title"><%= c.name %></h5>
            <%= link_to 'See details', cocktail_path(c)  %>
          </div>
        </div>
    </div>


    <% end %>
</div>
</div>

app/views/cocktails/new.html.erb
<%= simple_form_for(@cocktail) do |f| %>
  <div class="form-inputs">
    <%= f.input :name %>
    <%= f.input :photo %>
    <%= f.input :photo_cache, as: :hidden %>
  </div>

  <%= f.button :submit %>
<% end %>

app/views/cocktails/show.html.erb
<div class="container mt-3" id="cocktail-list">

  <h3 class="mb-3"><%= @cocktail.name %></h3>
  <%= link_to 'Delete this cocktail', cocktail_path(@cocktail), method: :delete, data: {confirm: 'Are you sure?'}, class: 'btn btn-danger'%>
  <div class="row">
<div class="col">
      <div class="card mb-3">
       <%= cl_image_tag @cocktail.photo %>
      </div>
    </div>
    <div class="col">
      <div class="container">
        <h5 class="card-title">Ingredients</h5>
        <% @cocktail.doses.each do |dose| %>
        <div class="card mb-3">
            <div class="card-body">
              <%= dose.description %> <%= dose.ingredient.name %>
              <%= link_to 'delete', dose_path(dose), method: :delete, data: {confirm: 'Are you sure?'}, class: 'far fa-trash-alt'%>

            </div>
          </div>
          <% end %>

            <p><%= link_to 'Add a dose', new_cocktail_dose_path(@cocktail) %></p>

      </div>
    </div>
</div>
</div>

app/views/doses/new.html.erb
<h1>Doses#new</h1>
<p>Find me in app/views/doses/new.html.erb</p>

<div class="container">
  <%= simple_form_for [@cocktail, @dose] do |f| %>
  <%= f.input :description %>
  <%= f.association :ingredient %>
  <%= f.submit 'Add to cocktail' %>
  <% end %>

  <%= link_to 'Back', cocktails_path %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Kaveh Cocktail Bar</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
  </head>

  <body>
    <nav class="navbar bg-light border-button-1">
      <%= link_to "Home", root_path, class: "btn btn-outline-warning" %>
      <%= link_to "Add a cocktail", new_cocktail_path, class: "btn btn-outline-warning" %>

    </nav>
    <%= yield %>
    <%= javascript_include_tag "application" %> <!-- from app/assets/javascripts/application.js -->
    <%= javascript_pack_tag "application" %>
  </body>
</html>